### ISSUE TITLE
The sharing of a position doesn't work on production

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.noi.maps#32]
**Describe the bug**
If I try to share a position with someone else the link I send opens the "home" of maps and not the right position on the map of NOI Techpark

**To Reproduce**
1. open maps.noi.bz.it
2. open the map of a floor
3. click on a clickable room
4.  click on share
5. click on copy link
6. open a new browser and paste the link

**Expected behavior**
The new browser should open maps.bz.it showing the details of the shared room

**Screenshots**

**Please complete the following information:**
- Browser tested:  Firefox v 101.0.1 (64 bit), Chrome v 103.0.5060.53 and Brave v. 1.40.107
- Language of your application: `it`, `de` and `en`
- Operating system: Ubuntu 20.04

**Additional info**
If I manually change the domain of the shared link from bz.it to testingmachine.eu the functionality works.

**Comment by Piiit** [comment]
@sseppi It should be fixed now... please test. I pushed it already to production, since the problem only occurred there. Should be fine, tested myself beforehand.

This solution is a hack though, most parts of this web component just have a timer to check for changes and "hope" that everything has been properly loaded, this should not be the way to go. I think, we should rewrite some logic of this component to "listen" to property-changes and to get the state of needed elements in the DOM. I will open some issues now...

If you are happy with the changes, just close it... it is already on production
